languageCode = "en-US"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Aurelien Tondoux"
copyright = "&copy; 2025 Aurelien Tondoux"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["samples"]
  description = "## description ##"

[params.author]
  name = "Aurelien Tondoux"
  image = "img/author.jpg"
  headline = "Full Stack Developer â€¢ Tech Lead"
  bio = "## bio ##"
  links = [
    { linkedin = "https://www.linkedin.com/in/atondoux" },
    { github = "https://github.com/atondoux" }
  ]
